# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_medical_questions_pair": "00_data.external.ipynb",
         "Pad_Chunk_Pair": "01_task_text_sim.ipynb",
         "Undict": "01_task_text_sim.ipynb",
         "BertTextCNN": "01_task_text_sim.ipynb",
         "TextSimTokenizer": "01_task_text_sim.ipynb",
         "BertTextCNNCallback": "01_task_text_sim.ipynb",
         "BertTextCNNLearner": "01_task_text_sim.ipynb"}

modules = ["data/external.py",
           "task/text_sim.py"]

doc_url = "https://numb3r303.github.io/nlp/"

git_url = "https://github.com/numb3r303/nlp/tree/master/"

def custom_doc_links(name): return None
